Change remote methods to resource methods
ballerina-platform/module-ballerinax-health.clients pull request #5
Opened 2023-05-16 08:58 UTC by ThishaniLucas

| Existing           | Changed to            | Sample usage                                                                |
|--------------------|-----------------------|-----------------------------------------------------------------------------|
|                    |                       |                                                                             |
| getById            | get /read/id          | fhirConnectorObj->/read/id(resType, id);                                    |
| getByVersion       | get /read/version     | fhirConnectorObj->/read/'version(resType, id = "123", 'version = 'version); |
| update             | put /fhirResource     | fhirConnectorObj->/fhirResource.put(resPayload);                            |
| patch              | patch /fhirResource   | fhirConnectorObj->/fhirResource.patch(resType, id, resPayload)              |
| delete             | delete /fhirResource  | fhirConnectorObj->/fhirResource.delete(resType, id);                        |
| getInstanceHistory | get /history/instance | fhirConnectorObj->/history/instance("Patient", "1234", {"_count": "10"});   |
| create             | post /fhirResource    | fhirConnectorObj->/fhirResource.post(resPayload);                           |
| search             | get /search/type      | fhirConnectorObj->/search/'type(resType, request.getQueryParams());         |
| getHistory         | get /history/type     | fhirConnectorObj->/history/'type("Patient", {_count: "10"});                |
| getConformance     | get /metadata         | fhirConnectorObj->/metadata();                                              |
| getAllHistory      | get /history          |                                                                             |
| searchAll          | get /search           |                                                                             |
| batchRequest       | post /batch           |                                                                             |
| transaction        | post /transaction     |                                                                             |
| nextBundle         | get /bundle/next      |                                                                             |

2023-05-18 13:22 UTC, rdulmina commented on fhir/tests/test.bal
> +    FHIRResponse res1 = check urlRewriteConnector->/metadata();
```suggestion
    FHIRResponse res1 = check urlRewriteConnector->/metadata;
```

2023-05-18 13:22 UTC, rdulmina commented on fhir/fhir_connector.bal
> +    isolated resource function get read/id(@display {label: "Resource Type"} ResourceType|string 'type,
If we don't need annotation to be attached to param `id` we can rewrite this method using path params as `isolated resource function get read/[string id](@display {label: ...` See https://ballerina.io/learn/by-example/http-path-param/

We can call this method like `check fhirConnector->/read/pat1(PATIENT);`

If `pat1` is a variable we can also do
```bal
string id = "pat1";
check fhirConnector->/read/[id](PATIENT);
```

2023-05-18 13:22 UTC, rdulmina commented on fhir/fhir_connector.bal
> +    isolated resource function get read/id(@display {label: "Resource Type"} ResourceType|string 'type,
Lets update similar places as well

2023-05-19 07:24 UTC, nirmal070125 requested changes
The changes to the operation names are still in discussion. Hold merging till we hear from the ballerina team.

2023-05-19 20:56 UTC, sameerajayasoma commented
I would use `fhir` or `fhir-resource` instead of `fhirResource` in the resource path.

2024-09-13 05:17 UTC, closed without merging