Upgrade Ballerina version to 2201.5.0
ballerina-platform/module-ballerinax-health.clients pull request #7
Opened 2023-05-30 05:56 UTC by Thiyanwso2

## Purpose
> $Subject

## Issues
> https://github.com/wso2-enterprise/open-healthcare/issues/1243

2023-05-30 06:05 UTC, AnjanaSenanayake approved these changes

2023-05-30 06:10 UTC, AnjanaSenanayake commented on fhir/Dependencies.toml
> +version = "1.0.2-snapshot"
Do we need the snapshot version?

2023-05-30 06:13 UTC, AnjanaSenanayake requested changes
Review snapshot dependencies added

2023-05-31 07:37 UTC, ThishaniLucas approved these changes

2023-05-31 07:38 UTC, Thiyanwso2 commented on fhir/Dependencies.toml
> +version = "1.0.2-snapshot"
Removed

2023-05-31 10:40 UTC, merged